version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always